### ISSUE TITLE
Bump .travis.yml from Node v5 to v6

### ISSUE THREAD

**Issue by pdehaan** [gregglind/shield-study-cli#12]
Node v5 isn't really supported, we should move to latest stable, which is currently v6.
Also not sure if the `TRAVIS` env variable is needed, since I think it's pre-baked into Travis already.

> ### Default Environment Variables
> 
> The following default environment variables are available to all builds.
> - `CI=true`
> - `TRAVIS=true`
> - `CONTINUOUS_INTEGRATION=true`

&mdash; via https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables

``` yml
sudo: false
language: node_js
node_js:
- "5.6"

env:
- TRAVIS=1

# before_install:
#  - cd to your src if needed

before_script:  # turn off screen
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 2 # give xvfb some time to start

addons:
  firefox: "latest"
notifications:
  email: false
```
